function designui(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Dc='.cache.html',_='/',lb='//',ic='36C621F92F73741CB7C2009BB281E98A',lc='3B718A5DEA9CC2C88257F48D9EF406E2',mc='71A0BDB48E9127D78635AAAB2481A894',qc='7B1950B98F0250C2673818DB110BD046',rc='7B1FE1CD29284F0A8601EBB78483DE8D',Bc='88AE91994FC08D74B2280D5D3C98D0F1',Cc=':',jc=':1',sc=':10',tc=':11',uc=':12',vc=':13',wc=':14',kc=':2',nc=':3',oc=':4',pc=':5',xc=':6',yc=':7',zc=':8',Ac=':9',pb='::',Lc='<script defer="defer">designui.onInjectionDone(\'designui\')<\/script>',hb='<script id="',sb='=',$='?',ub='Bad handler "',Kc='DOMContentLoaded',jb='SCRIPT',gb='__gwt_marker_designui',Xb='adobeair',Yb='air',kb='base',cb='baseUrl',T='begin',S='bootstrap',Db='chrome',bb='clear.cache.gif',rb='content',Q='designui',eb='designui.nocache.js',ob='designui::',Y='end',Tb='gecko',Vb='gecko1_8',Wb='gecko1_9',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',Ec='gwt/clean/clean.css',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',Cb='gxt.user.agent',Jc='head',gc='hosted.html?designui',Ic='href',Hb='ie6',Jb='ie7',Lb='ie8',Mb='ie9',yb='iframe',ab='img',zb="javascript:''",Fc='link',bc='linux',fc='loadExternalRefs',ac='mac',_b='mac os x',$b='macintosh',mb='meta',Bb='moduleRequested',X='moduleStartup',Fb='msie',Gb='msie 6',Ib='msie 7',Kb='msie 8',nb='name',Eb='opera',Ab='position:absolute;width:0;height:0;border:none',Gc='rel',Ub='rv:1.8',Nb='safari',Pb='safari3',Rb='safari4',Sb='safari5',db='script',hc='selectingPermutation',R='startup',Hc='stylesheet',fb='undefined',ec='unknown',Zb='user.agent.os',Ob='version/3',Qb='version/4',dc='win32',cc='windows';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}designui=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Db)!=-1)return Db;if(a.indexOf(Eb)!=-1)return Eb;if(a.indexOf(Fb)!=-1){if(a.indexOf(Gb)!=-1)return Hb;if(a.indexOf(Ib)!=-1)return Jb;if(a.indexOf(Kb)!=-1)return Lb;return Mb}if(a.indexOf(Nb)!=-1){if(a.indexOf(Ob)!=-1)return Pb;if(a.indexOf(Qb)!=-1)return Rb;return Sb}if(a.indexOf(Tb)!=-1){if(a.indexOf(Ub)!=-1)return Vb;return Wb}if(a.indexOf(Xb)!=-1)return Yb;return null};v[Cb]={air:0,chrome:1,gecko1_8:2,gecko1_9:3,ie6:4,ie7:5,ie8:6,ie9:7,opera:8,safari3:9,safari4:10,safari5:11};w[Zb]=function(){var a=m.navigator.userAgent.toLowerCase();if(a.indexOf($b)!=-1||a.indexOf(_b)!=-1){return ac}if(a.indexOf(bc)!=-1){return bc}if(a.indexOf(cc)!=-1||a.indexOf(dc)!=-1){return cc}return ec};v[Zb]={linux:0,mac:1,windows:2};designui.onScriptLoad=function(){if(I){r=true;C()}};designui.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:fc,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=gc;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:hc});if(!B()){try{G([Mb,bc],ic);G([Mb,ac],ic+jc);G([Mb,cc],ic+kc);G([Lb,bc],lc);G([Lb,ac],lc+jc);G([Lb,cc],lc+kc);G([Hb,bc],mc);G([Hb,ac],mc+jc);G([Hb,cc],mc+kc);G([Jb,bc],mc+nc);G([Jb,ac],mc+oc);G([Jb,cc],mc+pc);G([Eb,bc],qc);G([Eb,ac],qc+jc);G([Eb,cc],qc+kc);G([Yb,bc],rc);G([Yb,ac],rc+jc);G([Rb,ac],rc+sc);G([Rb,cc],rc+tc);G([Sb,bc],rc+uc);G([Sb,ac],rc+vc);G([Sb,cc],rc+wc);G([Yb,cc],rc+kc);G([Db,bc],rc+nc);G([Db,ac],rc+oc);G([Db,cc],rc+pc);G([Pb,bc],rc+xc);G([Pb,ac],rc+yc);G([Pb,cc],rc+zc);G([Rb,bc],rc+Ac);G([Vb,bc],Bc);G([Vb,ac],Bc+jc);G([Vb,cc],Bc+kc);G([Wb,bc],Bc+nc);G([Wb,ac],Bc+oc);G([Wb,cc],Bc+pc);K=x[H(Cb)][H(Zb)];var M=K.indexOf(Cc);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+Dc}catch(a){return}}var N;function O(){if(!s){s=true;if(!__gwt_stylesLoaded[Ec]){var a=n.createElement(Fc);__gwt_stylesLoaded[Ec]=a;a.setAttribute(Gc,Hc);a.setAttribute(Ic,t+Ec);n.getElementsByTagName(Jc)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(Kc,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(Kc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:fc,millis:(new Date).getTime(),type:T});n.write(Lc)}
designui();